---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Menu
- type: document
  path: pages/posts
  label: Post
- type: directory
  path: assets/img
  label: Main
  create: all
  match: "**/*"
  new_doc_ext: md
upload_dir: public/assets/img
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
